# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjN2b7k0Zm8D28B2NkeH-CSGFMFbrwR6

Assignment Day 7 - Web Scraping

> Hijir Della Wirasti

# Book Store
"""

import requests

import pandas as pd

"""Beautiful Soup"""

from bs4 import BeautifulSoup

books = []
for i in range(1,50):
  url = f'https://books.toscrape.com/catalogue/page-{i}.html'
  response = requests.get(url)
  response = response.content
  soup = BeautifulSoup(response, 'html.parser')
  ol = soup.find('ol') #untuk menemukan order list
  articles = soup.find_all('article', class_='product_pod')


  for article in articles:
    image = article.find('img')
    title = image.attrs['alt']
    star = article.find('p')
    star = star['class'][1]
    price = article.find('p', class_='price_color').text
    price = float(price [1:])
    books.append([title, price, star])

df = pd.DataFrame(books, columns=['Title', 'Price', 'Star'])

df.to_csv('books.csv')

"""# Quotes"""

import csv

page_to_scrape = requests.get('http://quotes.toscrape.com/')

soup = BeautifulSoup(page_to_scrape.content, 'html.parser')

quotes = soup.find_all('span', attrs={'class':'text'})

authors = soup.find_all('small', attrs={'class':'author'})

from os import write
file = open('quotes.csv', 'w')
writer = csv.writer(file)
writer.writerow(['Quotes', 'Authors'])

for quote, author in zip (quotes,authors):
  print(quote.text + ' - ' + author.text)
file.close()